name: Deploy to GitHub Pages

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync
          uv run playwright install --with-deps chromium
          make all-slides
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/revealjs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
